# -*-coding:utf-8-*-
from odoo import models, fields, api
from dossie import tipo_processo_vals, parecer_vals, responsabilidade_vals, dossie_state
from dossie import assuncao_defesa_vals, risco_vals, polo_cliente_vals, analise_acordo_vals, boolean_selection_vals
from lxml import etree
from odoo.osv.orm import setup_modifiers


class ProjectTaskActionLine(models.Model):
    _inherit = 'project.task.action.line'

    ########## TASK RELATED FIELDS ##########

    dossie_id = fields.Many2one( 
      store=True, 
      related='task_id.dossie_id')
    fase_tarefa_id = fields.Many2one(
      store=True,
      related='task_id.fase_tarefa_id')
    task_type_id = fields.Many2one(
      related='task_id.task_type_id', 
      store=True, 
      readonly=True)
    movimentacao_id = fields.Many2one(
      comodel_name='dossie.movimentacao', 
      string=u'Movimentação')
    movimentacao = fields.Text(
      store=True,
      readonly=True,
      related='movimentacao_id.movimentacao')
    currency_id = fields.Many2one(
        store=True,
        related='dossie_id.currency_id')

    ########## TASK RELATED FIELDS ##########    

    guia = fields.Many2one(
      store=True,
      related='task_id.guia')
    guia_paga = fields.Many2one(
      store=True,
      related='task_id.guia_paga')
    comprovante_protocolo = fields.Many2one(
      store=True,
      related='task_id.comprovante_protocolo')
    comprovante_pagamento = fields.Many2one(
      store=True,
      related='task_id.comprovante_pagamento')    
    documento_juntada = fields.Many2many(
      related='task_id.documento_juntada')
    guias_preparo = fields.Many2many(
      related='task_id.guias_preparo')
    tem_preparo = fields.Selection(
      store=True,
      related='task_id.tem_preparo')
    lote = fields.Char(
      store=True,
      related='task_id.lote')
    data_audiencia = fields.Datetime(
      store=True,
      related='task_id.data_audiencia')
    presentes_audiencia = fields.Selection(
      store=True,
      related='task_id.presentes_audiencia')
    correspondente_id = fields.Many2one(
      store=True,
      related='task_id.correspondente_id')
    valor_correspondente = fields.Monetary(
      store=True,
      related='task_id.valor_correspondente')
    valor_correspondente_media = fields.Monetary(
      string=u'Média Valor do Correspondente',
      related='valor_correspondente', 
      group_operator='avg', 
      readonly=True, 
      store=True)
    advogado_id = fields.Many2one(
      store=True,
      related='task_id.advogado_id')
    preposto_id = fields.Many2one(
      store=True,
      related='task_id.preposto_id')
    ata = fields.Many2one(
      store=True,
      related='task_id.ata')
    motivo_infrutividade = fields.Selection(
      store=True,
      related='task_id.motivo_infrutividade')
    tipo_pagamento = fields.Many2one(
      store=True,
      related='task_id.tipo_pagamento')
    tipo_acordo = fields.Selection(
      store=True,
      related='task_id.tipo_acordo')
    obrigacao = fields.Text(
      store=True,
      related='task_id.obrigacao')
    estado_sentenca = fields.Selection(
      store=True,
      related='task_id.estado_sentenca')
    forma_pagamento_id = fields.Many2one(
      store=True,
      related='task_id.forma_pagamento_id')
    relatorio_pagamento = fields.Many2one(
      store=True,
      related='task_id.relatorio_pagamento')
    peticao = fields.Many2one(
      store=True,
      related='task_id.peticao')
    tipo_prazo_id = fields.Many2one(
      store=True,
      related='task_id.tipo_prazo_id')
    tipo_transito_id = fields.Many2one(
      store=True,
      related='task_id.tipo_transito_id')
    copias = fields.Many2many(
      related='task_id.copias')
    tipo_recurso_id = fields.Many2one(
      store=True,
      related='task_id.tipo_recurso_id')
    tipo_dispensa = fields.Selection(
      store=True,
      related='task_id.tipo_dispensa')
    relatorio_dispensa = fields.Many2one(
      store=True,
      related='task_id.relatorio_dispensa')
    tem_multa_obrigacao = fields.Selection(
      store=True,
      related='task_id.tem_multa_obrigacao')
    comprovante_obrigacao = fields.Many2one(
      store=True,
      related='task_id.comprovante_obrigacao')
    motivo_nao_cumprimento = fields.Selection(
      store=True,
      related='task_id.motivo_nao_cumprimento')
    valor_protocolo = fields.Monetary(
      store=True,
      related='task_id.valor_protocolo')
    valor_protocolo_media = fields.Monetary(
      string=u'Média Valor Protocolo',
      related='valor_protocolo', 
      group_operator='avg', 
      readonly=True, 
      store=True)
    motivo_cancelamento_id = fields.Many2one(
      store=True,
      related='task_id.motivo_cancelamento_id')
    transitou = fields.Selection(
      store=True,
      related='task_id.transitou')
    tipo_audiencia = fields.Selection(
      store=True,
      related='task_id.tipo_audiencia')
    local_audiencia = fields.Char(
      store=True,
      related='task_id.local_audiencia')
    comprovante_repasse = fields.Many2one(
      store=True,
      related='task_id.comprovante_repasse')
    pedido_obrigacao = fields.Many2one(
      store=True,
      related='task_id.pedido_obrigacao')
    tipo_conclusao_documentos = fields.Selection(
      store=True,
      related='task_id.tipo_conclusao_documentos')
    conta_pagamento_id = fields.Many2one(
      store=True,
      related='task_id.conta_pagamento_id')
    tem_juntada = fields.Selection(
      store=True,
      related='task_id.tem_juntada')
    tem_citese = fields.Selection(
      store=True,
      related='task_id.tem_citese')
    tem_parecer = fields.Selection(
      store=True,
      related='task_id.tem_parecer')
    tem_emenda = fields.Selection(
      store=True,
      related='task_id.tem_emenda')
    tem_levantamento = fields.Selection(
      store=True,
      related='task_id.tem_levantamento')
    tem_obrigacao = fields.Selection(
      store=True,
      related='task_id.tem_obrigacao')
    tem_pagamento = fields.Selection(
      store=True,
      related='task_id.tem_pagamento')
    tem_levantamento_cliente = fields.Selection(
      store=True,
      related='task_id.tem_levantamento_cliente')
    tem_obrigacao_cliente = fields.Selection(
      store=True,
      related='task_id.tem_obrigacao_cliente')
    tem_pagamento_cliente = fields.Selection(
      store=True,
      related='task_id.tem_pagamento_cliente')
    tem_dispensa = fields.Selection(
      store=True,
      related='task_id.tem_dispensa')
    precisa_copias = fields.Selection(
      store=True,
      related='task_id.precisa_copias')
    tem_baixa_restritivo = fields.Selection(
      store=True,
      related='task_id.tem_baixa_restritivo')
    valor_contraproposta = fields.Monetary(
      store=True,
      related='task_id.valor_contraproposta')
    valor_contraproposta_media = fields.Monetary(
      string=u'Média Valor Contraproposta',
      related='valor_contraproposta', 
      group_operator='avg', 
      readonly=True, 
      store=True)
    valor_preparo = fields.Monetary(
      store=True,
      related='task_id.valor_preparo')
    valor_preparo_media = fields.Monetary(
      string=u'Média Valor Custas',
      related='valor_preparo', 
      group_operator='avg', 
      readonly=True, 
      store=True)
    numero_recibo = fields.Char(
      store=True,
      related='task_id.numero_recibo')
    data_prevista_sentenca = fields.Date(
      store=True,
      related='task_id.data_prevista_sentenca')
    area_oficio_id = fields.Many2one(
      store=True,
      related='task_id.area_oficio_id')
    tem_audiencia = fields.Selection(
      store=True,
      related='task_id.tem_audiencia')
    tem_cedula = fields.Selection(
      store=True,
      related='task_id.tem_cedula')
    tem_prescricao = fields.Selection(
      store=True,
      related='task_id.tem_prescricao')
    tem_extrato = fields.Selection(
      store=True,
      related='task_id.tem_extrato')
    tem_veiculo = fields.Selection(
      store=True,
      related='task_id.tem_veiculo')
    tem_endereco = fields.Selection(
      store=True,
      related='task_id.tem_endereco')
    tem_telefone = fields.Selection(
      store=True,
      related='task_id.tem_telefone')
    citacao_deferida = fields.Selection(
      store=True,
      related='task_id.citacao_deferida')
    data_citacao_deferida = fields.Date(
      store=True,
      related='task_id.data_citacao_deferida')
    citacao_expedida = fields.Selection(
      store=True,
      related='task_id.citacao_expedida')
    data_citacao_expedida = fields.Date(
      store=True,
      related='task_id.data_citacao_expedida')
    citacao_efetivada = fields.Selection(
      store=True,
      related='task_id.citacao_efetivada')
    data_citacao_efetivada = fields.Date(
      store=True,
      related='task_id.data_citacao_efetivada')
    tem_bens = fields.Selection(
      store=True,
      related='task_id.tem_bens')
    penhora_deferida = fields.Selection(
      store=True,
      related='task_id.penhora_deferida')
    data_penhora_deferida = fields.Date(
      store=True,
      related='task_id.data_penhora_deferida')
    penhora_efetivada = fields.Selection(
      store=True,
      related='task_id.penhora_efetivada')
    data_penhora_efetivada = fields.Date(
      store=True,
      related='task_id.data_penhora_efetivada')
    recibo_anexo = fields.Many2one(
      store=True,
      related='task_id.recibo_anexo')
    dossie_citacao_id = fields.Many2one(
      store=True,
      related='task_id.dossie_citacao_id')
    dossie_citacao_parte_contraria_ids = fields.Many2many(
      related='task_id.dossie_citacao_parte_contraria_ids')
    dossie_resultado_parte_ids = fields.One2many(
      related='task_id.dossie_resultado_parte_ids')
    dossie_penhora_id = fields.Many2one(
      store=True,
      related='task_id.dossie_penhora_id')
    dossie_penhora_tipo_ids = fields.Many2many(
      related='task_id.dossie_penhora_tipo_ids')
    dossie_penhora_bem_ids = fields.Many2many( 
      related='task_id.dossie_penhora_bem_ids')
    tipos_obrigacoes_ids = fields.Many2many(
      related='task_id.tipos_obrigacoes_ids')
    tem_contestacao = fields.Selection(
      store=True,
      related='task_id.tem_contestacao')
    precisa_documento = fields.Selection(
      store=True,
      related='task_id.precisa_documento')
    tipos_documentos_ids = fields.Many2many(
      related='task_id.tipos_documentos_ids')
    observacoes_documentos = fields.Text(
      store=True,
      related='task_id.observacoes_documentos')
    documentos_solicitado_ids = fields.Many2many(
      related='task_id.documentos_solicitado_ids')
    observacoes_copias = fields.Text(
      store=True,
      related='task_id.observacoes_copias')
    valor_pagamento = fields.Monetary(
      store=True,
      related='task_id.valor_pagamento')
    valor_pagamento_media = fields.Monetary(
      string=u'Média Valor do Pagamento',
      related='valor_pagamento', 
      group_operator='avg', 
      readonly=True, 
      store=True)
    resultado_negociacao = fields.Selection(
      store=True,
      related='task_id.resultado_negociacao')
    tem_multa_pagamento = fields.Selection(
      store=True,
      related='task_id.tem_multa_pagamento')
    guias_pagas_custas = fields.Many2many(
      related='task_id.guias_pagas_custas')
    precisa_prazo = fields.Selection(
      store=True,
      related='task_id.precisa_prazo')
    precisa_recurso = fields.Selection(
      store=True,
      related='task_id.precisa_recurso')
    tipo_encerramento_id = fields.Many2one(
      store=True,
      related='task_id.tipo_encerramento_id')
    encerrado_cliente = fields.Selection(
      store=True,
      related='task_id.encerrado_cliente')
    related_tipo_sentenca_id = fields.Many2one(
      related='tipo_sentenca_id')
    related_analise_acordo = fields.Selection(
      related='analise_acordo')
    related_valor_alcada = fields.Monetary(
      related='valor_alcada')
    related_motivo_inaptidao = fields.Many2one(
      related='motivo_inaptidao')
    related_tipo_prazo_id = fields.Many2one(
      related='tipo_prazo_id')
    related_obrigacao_alcada = fields.Text(
      related='obrigacao_alcada')
    related_tipo_recurso_id = fields.Many2one(
      related='tipo_recurso_id')
    copias_aprovado = fields.Selection(
      store=True,
      related='task_id.copias_aprovado')
    cancelamento_aprovado = fields.Selection(
      store=True,
      related='task_id.cancelamento_aprovado')
    tem_audiencia_redesignada = fields.Selection(
      store=True,
      related='task_id.tem_audiencia_redesignada')
    data_audiencia_redesignada = fields.Datetime(
      store=True,
      related='task_id.data_audiencia_redesignada')
    tem_proxima_audiencia = fields.Selection(
      store=True,
      related='task_id.tem_proxima_audiencia')
    data_proxima_audiencia = fields.Datetime(
      store=True,
      related='task_id.data_proxima_audiencia')
    tem_sucumbencia = fields.Selection(
      store=True,
      related='task_id.tem_sucumbencia')
    valor_sucumbencia = fields.Monetary(
      store=True,
      related='task_id.valor_sucumbencia')
    cedula_anexo = fields.Many2one(
      store=True,
      related='task_id.cedula_anexo')
    extrato_anexo = fields.Many2one(
      store=True,
      related='task_id.extrato_anexo')
    tem_planilha_debito = fields.Selection(
      store=True,
      related='task_id.tem_planilha_debito')
    planilha_debito_anexo = fields.Many2one(
      store=True,
      related='task_id.planilha_debito_anexo')
    related_contrato_id = fields.Many2one(
      related='contrato_id')
    related_parecer = fields.Selection(
      related='parecer')
    related_relatorio_parecer = fields.Many2one(
      related='relatorio_parecer')
    analise_parecer = fields.Selection(
      store=True,
      related='task_id.analise_parecer')
    analise_parecer_observacoes = fields.Text(
      store=True,
      related='task_id.analise_parecer_observacoes')
    related_citacao_id = fields.Many2one(
      related='citacao_id')
    related_liminar_id = fields.Many2one(
      related='liminar_id')
    related_sentenca_id = fields.Many2one(
      related='sentenca_id')
    related_acordao_id = fields.Many2one(
      related='acordao_id')
    
    ########## DOSSIÊ RELATED FIELDS ##########


    dossie_state = fields.Selection(
      store=True, 
      related='dossie_id.state')
    fase_id = fields.Many2one(
      store=True,
      related='dossie_id.fase_id')
    polo_cliente = fields.Selection(
      store=True, 
      related='dossie_id.polo_cliente')

    numero_pendencias = fields.Integer(
      store=True, 
      related='dossie_id.numero_pendencias')

    dossie_name = fields.Char(
      store=True, 
      related='dossie_id.name')
    origem_id = fields.Many2one(
      store=True, 
      related='dossie_id.origem_id')
    processo = fields.Char(
      store=True, 
      related='dossie_id.processo')
    tipo_processo = fields.Selection(
      store=True, 
      related='dossie_id.tipo_processo')

    parte_representada_ids = fields.Many2many(
      related='dossie_id.parte_representada_ids')
    parte_contraria_ids = fields.Many2many(
      related='dossie_id.parte_contraria_ids')
    parte_contraria_contumaz_ids = fields.Many2many(
      related='dossie_id.parte_contraria_contumaz_ids')
    tem_advogado = fields.Selection(
      store=True, 
      related='dossie_id.tem_advogado')
    escritorio_id = fields.Many2one(
      store=True, 
      related='dossie_id.escritorio_id')
    advogado_adverso_ids = fields.Many2many(
      related='dossie_id.advogado_adverso_ids')
    advogado_adverso_agressor_ids = fields.Many2many(
      related='dossie_id.advogado_adverso_agressor_ids')
    assuncao_defesa = fields.Selection(
      store=True,
      related='dossie_id.assuncao_defesa')

    valor_causa = fields.Monetary(
      store=True, 
      related='dossie_id.valor_causa')
    valor_dano_moral = fields.Monetary(
      store=True,
      related='dossie_id.valor_dano_moral')
    valor_dano_material = fields.Monetary(
      store=True,
      related='dossie_id.valor_dano_moral')

    rito_id = fields.Many2one(
      store=True, 
      related='dossie_id.rito_id')
    natureza_id = fields.Many2one(
      store=True, 
      related='dossie_id.natureza_id')
    tipo_acao_id = fields.Many2one(
      store=True, 
      related='dossie_id.tipo_acao_id')

    ordinal = fields.Integer(
      store=True,
      related='dossie_id.ordinal')
    vara_id = fields.Many2one(
      store=True, 
      related='dossie_id.vara_id')
    orgao_id = fields.Many2one(
      store=True, 
      related='dossie_id.orgao_id')
    comarca_id = fields.Many2one(
      store=True, 
      related='dossie_id.comarca_id')
    estado_id = fields.Many2one(
      store=True, 
      related='dossie_id.estado_id')
    
    objeto_id = fields.Many2one(
      store=True, 
      related='dossie_id.objeto_id')
    assunto_id = fields.Many2one(
      store=True, 
      related='dossie_id.assunto_id')
    local_fato = fields.Char(
      store=True,
      related='dossie_id.local_fato')
    data_fato = fields.Date(
      store=True,
      related='dossie_id.data_fato')

    parecer = fields.Selection(
      store=True, 
      related='dossie_id.parecer')
    relatorio_parecer = fields.Many2one(
      store=True,
      readonly=True,
      related='dossie_id.relatorio_parecer')
    
    analise_acordo = fields.Selection(
      store=True,
      related='dossie_id.analise_acordo')
    motivo_inaptidao = fields.Many2one(
      store=True, 
      related='dossie_id.motivo_inaptidao')
    valor_alcada = fields.Monetary(
      store=True, 
      related='dossie_id.valor_alcada')
    obrigacao_alcada = fields.Text(
      store=True, 
      related='dossie_id.obrigacao_alcada')

    grupo_id = fields.Many2one(
      store=True, 
      related='dossie_id.grupo_id')
    projeto_id = fields.Many2one(
      store=True, 
      related='dossie_id.projeto_id')
    credenciado_id = fields.Many2one(
      store=True, 
      related='dossie_id.credenciado_id')
    
    contrato_id = fields.Many2one(
      store=True, 
      related='dossie_id.contrato_id')
    contrato_tipo_id = fields.Many2one(
      store=True,
      related='dossie_id.contrato_tipo_id')
    contrato = fields.Char(
      store=True,
      related='dossie_id.contrato')
    carteira_id = fields.Many2one(
      store=True, 
      related='dossie_id.carteira_id')
    risco = fields.Selection(
      store=True, 
      related='dossie_id.risco')
    responsabilidade = fields.Selection(
      store=True, 
      related='dossie_id.responsabilidade')
    cessionaria_id = fields.Many2one(
      store=True, 
      related='dossie_id.cessionaria_id')
    '''
    task_ids = fields.One2many(
        inverse_name='dossie_id',
        store=True,
        related='dossie_id.task_ids')
    '''
    inicial = fields.Text(
      store=True, 
      related='dossie_id.inicial')
    inicial_id = fields.Many2one(
      store=True, 
      related='dossie_id.inicial_id', 
      readonly=True)
    data_distribuicao = fields.Date(
      store=True, 
      related='dossie_id.data_distribuicao')

    citacao = fields.Text(
      store=True, 
      related='dossie_id.citacao')
    citacao_id = fields.Many2one(
      store=True, 
      related='dossie_id.citacao_id', 
      readonly=True)
    data_citacao = fields.Date(
      store=True,
      related='dossie_id.data_citacao')

    liminar_id = fields.Many2one(
      store=True,
      related='dossie_id.liminar_id')
    liminar = fields.Text(
      store=True,
      related='liminar_id.liminar')
    liminar_anexo_id = fields.Many2one(
      store=True,
      related='liminar_id.anexo_id')
    data_liminar = fields.Date(
      store=True,
      related='liminar_id.data')

    sentenca_id = fields.Many2one(
      store=True,
      related='dossie_id.sentenca_id')
    sentenca = fields.Text(
      store=True, 
      related='sentenca_id.sentenca')
    sentenca_anexo_id = fields.Many2one(
      store=True,
      related='sentenca_id.anexo_id',
      readonly=True)
    data_sentenca = fields.Date(
      store=True, 
      related='sentenca_id.data')
    tipo_sentenca_id = fields.Many2one(
      store=True,
      related='sentenca_id.tipo_sentenca_id')

    acordao_id = fields.Many2one(
      store=True, 
      related='dossie_id.acordao_id')
    acordao_anexo_id = fields.Many2one(
        store=True,
        related='acordao_id.anexo_id')
    acordao = fields.Text(
      store=True, 
      related='acordao_id.acordao')
    data_acordao = fields.Date(
      store=True, 
      related='acordao_id.data')
    tipo_acordao_id = fields.Many2one(
      store=True,
      related='acordao_id.tipo_acordao_id')

    acordao_superior_id = fields.Many2one(
      store=True,
      related='dossie_id.acordao_superior_id', 
      readonly=True)
    acordao_superior = fields.Text( 
      store=True,
      related='dossie_id.acordao_superior')
    data_acordao_superior = fields.Date(
      store=True,
      related='dossie_id.data_acordao_superior')
    tipo_acordao_superior_id = fields.Many2one(
      store=True,
      related='dossie_id.tipo_acordao_superior_id')

    acordao_supremo = fields.Text(
      store=True,
      related='dossie_id.acordao_supremo')
    acordao_supremo_id = fields.Many2one(
      store=True,
      related='dossie_id.acordao_supremo_id', 
      readonly=True)
    data_acordao_supremo = fields.Date(
      store=True, 
      related='dossie_id.data_acordao_supremo')
    tipo_acordao_supremo_id = fields.Many2one(
      store=True,
      related='dossie_id.tipo_acordao_supremo_id')

    movimentacao_historico_ids = fields.One2many(
      inverse_name='dossie_id',
      store=True,
      related='dossie_id.movimentacao_historico_ids')

    fase_cliente =  fields.Char(
      related='dossie_id.fase_cliente')
